repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: ["--extend-select", "I", "--fix"]
        exclude: __init__.py
      - id: ruff-format
        exclude: __init__.py
