name: 'Setup cuequivariance-jax'
description: 'Install cuequivariance-jax with all JAX dependencies'

inputs:
  use-gpu:
    description: 'Install GPU dependencies (jax[cuda12], CUDA ops packages)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install JAX (CPU)
      if: inputs.use-gpu != 'true'
      shell: bash
      run: |
        python -m uv pip install -U pytest jax
    
    - name: Install JAX (GPU)
      if: inputs.use-gpu == 'true'
      shell: bash
      run: |
        python -m uv pip install -U pytest "jax[cuda12]"
        python -m uv pip install nvidia-cusolver-cu12==11.7.3.90
        python -m uv pip install nvidia-cublas-cu12
    
    - name: Install common dependencies
      shell: bash
      run: |
        python -m uv pip install triton
        python -m uv pip install "flax>=0.12.0"
    
    - name: Install cuequivariance_ops
      shell: bash
      run: |
        # Try to install cuequivariance_ops from various possible locations
        # This handles cases where kernelcatcher is checked out as a sibling repo or submodule
        INSTALLED=false
        for path in "../cuequivariance_ops" "../../cuequivariance_ops" "../kernelcatcher/cuequivariance_ops" "./kernelcatcher/cuequivariance_ops"; do
          if [ -d "$path" ] && [ -f "$path/pyproject.toml" ]; then
            echo "Found cuequivariance_ops at $path, attempting installation..."
            # Install in editable mode - Python modules should work even if CUDA build fails
            # We allow the build to fail (CUDA not available) but Python modules should still be importable
            python -m uv pip install -e "$path" 2>&1 | tee /tmp/cue_ops_install.log || {
              echo "Installation had errors, but checking if Python modules are available..."
              # Even if build fails, Python modules might be available
              python -c "import cuequivariance_ops.triton" 2>/dev/null && INSTALLED=true || echo "Python modules not available"
            }
            if python -c "import cuequivariance_ops.triton" 2>/dev/null; then
              INSTALLED=true
              echo "Successfully installed cuequivariance_ops (Python modules available)"
              break
            fi
          fi
        done
        if [ "$INSTALLED" = "false" ]; then
          echo "Warning: cuequivariance_ops not found or installation failed. Some tests may be skipped."
        fi
    
    - name: Clean and install packages
      shell: bash
      run: |
        python -m uv pip uninstall cuequivariance cuequivariance_jax cuequivariance_torch 2>/dev/null || true
        python -m uv pip install -e ./cuequivariance
        python -m uv pip install -e ./cuequivariance_jax
    
    - name: Verify installation
      shell: bash
      run: |
        python -c "import cuequivariance; print('cue', cuequivariance.__version__)"
        python -c "import cuequivariance_jax; print('cuex', cuequivariance_jax.__version__)"
