name: Coverage on PR

on:
  pull_request:
    branches: [ "main", "release" ]


jobs:
  cuequivariance:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade uv
        python -m uv pip install pytest pytest-cov
        python -m uv pip install ./cuequivariance
    - name: Run coverage on PR branch
      run: |
        pytest --cov=cuequivariance cuequivariance > coverage.txt
        coverage_pr=$(cat coverage.txt | grep TOTAL | awk '{print $4}' | sed 's/%//')
        echo "Coverage on PR branch: $coverage_pr"
    - name: Run coverage on main branch
      run: |
        git fetch origin main:main
        git checkout main
        pytest --cov=cuequivariance cuequivariance > coverage.txt
        coverage_main=$(cat coverage.txt | grep TOTAL | awk '{print $4}' | sed 's/%//')
        echo "Coverage on main branch: $coverage_main"
    - name: Compare coverage
      run: |
        if [ $coverage_pr -lt $coverage_main ]; then
          echo "Coverage on PR branch is lower than on main branch"
          echo "Coverage on PR branch: $coverage_pr"
          echo "Coverage on main branch: $coverage_main"
          exit 1
        fi
