name: pull request workflow (gha)

on:
  push:
    branches:
      - "pull-request/[0-9]+"

jobs:

  runner-info:
    runs-on: linux-amd64-gpu-t4-latest-1
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: System Information
      run: |
        echo "=== System Information ==="
        uname -a
        cat /etc/os-release
        echo ""
        
        echo "=== CPU Information ==="
        lscpu | head -20
        echo ""
        
        echo "=== Memory Information ==="
        free -h
        echo ""
        
        echo "=== Disk Information ==="
        df -h
        echo ""
        
        echo "=== GPU Information ==="
        nvidia-smi || echo "nvidia-smi not available"
        echo ""
        
        echo "=== CUDA Information ==="
        nvcc --version || echo "CUDA compiler not available"
        echo ""
        
        echo "=== Python Environment ==="
        python3 --version || echo "Python3 not available"
        which python3 || echo "Python3 not in PATH"
        echo ""
        
        echo "=== Environment Variables ==="
        env | grep -E "(CUDA|GPU|NVIDIA)" || echo "No CUDA/GPU environment variables"
        echo ""
        
        echo "=== Docker Information ==="
        docker --version || echo "Docker not available"
        echo ""
