name: Upload Python Package

on:
  release:
    types: [published]

  workflow_dispatch:


permissions:
  contents: read


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatchling twine

    - name: Build & Publish cuequivariance
      working-directory: cuequivariance
      run: |
        hatchling build
        twine upload dist/*

    - name: Build & Publish cuequivariance-jax
      working-directory: cuequivariance_jax
      run: |
        hatchling build
        twine upload dist/*

    - name: Build & Publish cuequivariance-torch
      working-directory: cuequivariance_torch
      run: |
        hatchling build
        twine upload dist/*
