name: Run Style Check (Pre-commit)

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main", "release" ]


jobs:
  style:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Setup Pre-commit
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade uv
        python -m uv pip install pre-commit
        pre-commit install
    - name: Run Pre-commit
      run: |
        pre-commit run --all-files
